### ISSUE TITLE
python import question

### ISSUE THREAD

**Issue by geofflangenderfer** [jonathan-laurent/pyml_example#1]
in `test/test.py` we do
```
from pyml_example import random_expr, evaluate, random_expr_, evaluate_, map_array
```

and in `pyml_example/__init__.py` we do
```
from example_module import random_expr, evaluate, random_expr_, evaluate_, map_array
```
directory structure:
```
.
├── Makefile
├── README.md
├── _build
│   ├── default
│   │   └── ocaml
│   │       ├── expr.ml
│   │       ├── pywrap.ml
│   │       └── pywrap.so
│   └── log
├── build
│   └── lib
│       └── pyml_example
│           ├── __init__.py
│           └── pywrap.so
├── ocaml
│   ├── dune
│   ├── dune-project
│   ├── expr.ml
│   └── pywrap.ml
├── pyml_example
│   ├── __init__.py
│   └── pywrap.so
├── question.md
├── setup.py
└── test
    └── test.py

9 directories, 17 files

```

I have some questions:
- what is `pyml_example` pointing to?
- `example_module`?
- Why the difference?

**Comment by jonathan-laurent** [comment]
Great question!

- `pyml_example` is simply the name of the python package that I am creating to wrap the OCaml library that is to be exposed to users. Following the Python conventions, there is a `__init__.py` file in the directory of the same name and a `setup.py` file to build and install it. The package is used in `test.py` as an example.
- The `example_module` module is not defined on the Python side but on the OCaml side in [pywrap.so](https://github.com/jonathan-laurent/pyml_example/blob/6bcb61faf09756089b207266c0487182c076c772/ocaml/pywrap.ml#L84). It gets registered within the [call](dll.caml_startup(argv)) to `caml_startup` in `pyml_example/__init__.py`. This is the module that contains all the wrapped OCaml functions (that are also registered in pywrap.so) and these functions are "reexported" by the following statement: `from example_module import random_expr, evaluate, random_expr_, evaluate_, map_array`.

The summary here is that I am wrapping the OCaml-defined `example_module` module in a `pyml_example` Python package. Why am I doing this?

- It enables exposing a standard Python package to the user and taking care of the details of building it / starting the OCaml runtime in `pyml_example`.
- In practice, one may want to wrap the OCaml functions further (so as to provide typing annotations for example), which can be done naturally in `pyml_example.py`.

I hope this clarifies the situation.

**Comment by geofflangenderfer** [comment]
I'm trying to expose ocaml-defined functions in python. My strategy is:
- write desired python calls, similar to `test/test.py`
- work backwards from there following this example

Thanks for making this!

**Comment by jonathan-laurent** [comment]
Always happy to help!
Of course, most credit goes to the developers of pyml and pythonlib.

May I ask about what your usecase is for interfacing OCaml and Python. I am curious.

**Comment by geofflangenderfer** [comment]
I want to practice data structures and algorithms with ocaml and python.

Rather than rewrite in ocaml, I'd like to use pyml/pythonlib to reuse python infra code from a question judge  

I've tried Js_of_ocaml with no luck so far.

**Comment by geofflangenderfer** [comment]
I don't understand `let%map_open`, so I've taken a step back to learn about monads.

Am I on target or off course?

**Comment by jonathan-laurent** [comment]
`let%map_open` does not have to do with monads. It is syntactic sugar to call `map`, see the [documentation](https://github.com/janestreet/ppx_let).

The way pythonlib uses this to work internally is pretty subtle and I would argue you probably do not need to understand it deeply to work with Pythonlib.

**Comment by geofflangenderfer** [comment]
let me know if the questions become too much. I could also try discuss.ocaml.org

Is this `evaluate` pseudocode correct?:

- receive `random_expr(depth)` from `test/test.py`
- convert python value -> `expr`  using `expr_of_python`
- assign result to `e` 
- send `e` to `Expr.eval`
- use `python_of_int` to convert ocaml to python value
- return python `int` to original caller in `test/test.py`


```
# test/test.py
...
def profile(n=10_000, depth=5):
    t = timeit.Timer(lambda: evaluate(random_expr(depth))).timeit(n)
...
```

```
(* ocaml/pywrap.ml*)
(* this is a type?*)
type expr = [%import: Expr.expr [@with Base.int := int]] [@@deriving python]

(* this converts python value -> expr?*)
let expr =
  Defunc.Of_python.create
    ~type_name:"expr"
    ~conv:expr_of_python
...

let evaluate =
  let%map_open e = positional "e" expr ~docstring:"expression to evaluate" in
  python_of_int (Expr.eval e)
```

**Comment by geofflangenderfer** [comment]
I wrapped understanding what's going on in a Promise :) to be continued..

I got it to work!:
- I copied your folder structure letter for letter
- then added my own function to `ocaml/expr.ml`
- adding my own variable names was too much mental overhead as I compared yours and mine


My issue now is re-building after making changes to `ocaml/expr.ml`:
- `test/test.py` seems to be importing a stale copy of `pyml_example/pywrap.so`
- I tried `make clean && make build && python test/test.py`

Any thoughts?

**Comment by jonathan-laurent** [comment]
You want to use `make install` instead of `make build`. Indeed, you need to install the `pyml_example` package before you use it in `test.py`.

**Comment by geofflangenderfer** [comment]
> You want to use `make install` instead of `make build`. Indeed, you need to install the `pyml_example` package before you use it in `test.py`.

`make install && python test/test.py` did the trick!
